remote_theme: ankitsultana/researcher@gem

title: Conor James Thomas Warford Henry
url: "https://conrad141.github.io"
baseurl: "/about/"

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
